server:
  port: 8080
spring:
  datasource:
    username: root
    password: AllMightBoGdaN2003
    url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
indexing-settings:
  sites:
    - url: http://www.playback.ru
      name: PlayBack.Ru
    - url: https://et-cetera.ru
      name: et-cetera.ru
#    - url: https://dimonvideo.ru
#      name: dimonvideo
#    - url: https://skillbox.ru
#      name: Skillbox

